# ABDUL REHMAN
## E-mail: a.rehmanmemon.034@gmail.com
### Date Of Submission: 29/03/2023

##Task 10

Topics: Introduction to Numpy, Numpy Arrays

Resource: https://drive.google.com/file/d/1ILp88f3u_KgJ_nlhTSsAVGdmZlICGhhd/view?usp=share_link

Directions: Learn about Numpy arrays and try to make with single and multi dimensions, perform simple arithmetic operations using two multi dimensional arrays. Submit these practiced tasks on GitHub.

#CHAPTER 4 NumPy Basics: Arrays and Vectorized Computation

In [2]:
import numpy as np

In [4]:

#1d array
arr2=np.array([12,31,23,34])
print("First element of arr1: ",arr1[0])
print("total numbers in arr1: ",len(arr1))
arr3=np.array([12,31,23,34])
# Sum the two 1D arrays
arr_sum = arr2 + arr3

# Subtract the two 1D arrays
arr_diff = arr2 - arr3

# Multiply the two 1D arrays
arr_prod = arr2 * arr3

# Divide the two 1D arrays
arr_div = arr2 / arr3

# Print the arrays and their results

print("1D array 1: \n", arr2)
print("1D array 2: \n", arr3)
print("Addition result: \n", arr_sum)
print("Subtraction result: \n", arr_diff)
print("Multiplication result: \n", arr_prod)
print("Division result: \n", arr_div)

Exercise 4.1
First element of arr1:  12
total numbers in arr1:  4
1D array 1: 
 [12 31 23 34]
1D array 2: 
 [12 31 23 34]
Addition result: 
 [24 62 46 68]
Subtraction result: 
 [0 0 0 0]
Multiplication result: 
 [ 144  961  529 1156]
Division result: 
 [1. 1. 1. 1.]


In [5]:
# Create a 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Create another 2D array
arr3 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

# Add the two 2D arrays
arr_sum = arr2 + arr3

# Subtract the two 2D arrays
arr_diff = arr2 - arr3

# Multiply the two 2D arrays
arr_prod = arr2 * arr3

# Divide the two 2D arrays
arr_div = arr2 / arr3

# Print the arrays and their results

print("2D array 1: \n", arr2)
print("2D array 2: \n", arr3)
print("Addition result: \n", arr_sum)
print("Subtraction result: \n", arr_diff)
print("Multiplication result: \n", arr_prod)
print("Division result: \n", arr_div)

2D array 1: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
2D array 2: 
 [[9 8 7]
 [6 5 4]
 [3 2 1]]
Addition result: 
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
Subtraction result: 
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
Multiplication result: 
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]
Division result: 
 [[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]


In [6]:
# Create a 3D array
arr3d_1 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
arr3d_2 = np.array([[[8, 7], [6, 5]], [[4, 3], [2, 1]]])

# Add the two 3D arrays
arr_sum = arr3d_1 + arr3d_2

# Subtract the two 3D arrays
arr_diff = arr3d_1 - arr3d_2

# Multiply the two 3D arrays
arr_prod = arr3d_1 * arr3d_2

# Divide the two 3D arrays
arr_div = arr3d_1 / arr3d_2

# Print the arrays and their results
print("3D array 1: \n", arr3d_1)
print("3D array 2: \n", arr3d_2)
print("Addition result: \n", arr_sum)
print("Subtraction result: \n", arr_diff)
print("Multiplication result: \n", arr_prod)
print("Division result: \n", arr_div)

3D array 1: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3D array 2: 
 [[[8 7]
  [6 5]]

 [[4 3]
  [2 1]]]
Addition result: 
 [[[9 9]
  [9 9]]

 [[9 9]
  [9 9]]]
Subtraction result: 
 [[[-7 -5]
  [-3 -1]]

 [[ 1  3]
  [ 5  7]]]
Multiplication result: 
 [[[ 8 14]
  [18 20]]

 [[20 18]
  [14  8]]]
Division result: 
 [[[0.125      0.28571429]
  [0.5        0.8       ]]

 [[1.25       2.        ]
  [3.5        8.        ]]]


In [7]:

# Create a 3D array
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

# Slice the 3D array to get a 2D array
slice_2d = arr3d[0,:,:]

# Slice the 3D array to get a 1D array
slice_1d = arr3d[0,0,:]

# Print the arrays and their results
print("3D array: \n", arr3d)
print("2D slice: \n", slice_2d)
print("1D slice: \n", slice_1d)

3D array: 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
2D slice: 
 [[1 2 3]
 [4 5 6]]
1D slice: 
 [1 2 3]


In [8]:
# Create two matrices
A = np.array([[1, 2], [3, 4], [5, 6]])
B = np.array([[7, 8], [9, 10]])

# Compute their matrix product using the dot function
C_dot = np.dot(A, B)

# Compute their matrix product using the @ operator
C_at = A @ B

# Print the results
print("A:\n", A)
print("B:\n", B)
print("A dot B:\n", C_dot)
print("A @ B:\n", C_at)

A:
 [[1 2]
 [3 4]
 [5 6]]
B:
 [[ 7  8]
 [ 9 10]]
A dot B:
 [[ 25  28]
 [ 57  64]
 [ 89 100]]
A @ B:
 [[ 25  28]
 [ 57  64]
 [ 89 100]]


In [9]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [10]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

# The End 😃