# ABDUL REHMAN
## E-mail: a.rehmanmemon.034@gmail.com
### Date Of Submission: 31/03/2023

#Task 12

Topics: Broadcasting in Numpy Array

Resource: https://drive.google.com/file/d/1ILp88f3u_KgJ_nlhTSsAVGdmZlICGhhd/view?usp=share_link

Directions: The Broadcasting concepts are available in Numpy Appendix A: Advanced Numpy Section of the resource.

In [1]:
import numpy as np

In [5]:
print('Broadcasting with a scalar value:')
a = np.array([1, 2, 3])
b = 2
c = a + b
print(c)

Broadcasting with a scalar value:
[3 4 5]


In [6]:
print('Broadcasting with higher-dimensional arrays:')
a = np.array([[1, 2], [3, 4]])
b = np.array([10, 20])
c = a + b
print(c)

Broadcasting with higher-dimensional arrays:
[[11 22]
 [13 24]]


In [7]:
print('Broadcasting with mismatched shapes:')
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20])
c = a + b.reshape(-1, 1)

print('b:',b)

print("result:",c)

Broadcasting with mismatched shapes:
b: [10 20]
result: [[11 12 13]
 [24 25 26]]


# The End 😃